version: "3"
services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manufacturer
  manufacturers:
    image: ejmric/manufacturers
    ports:
      - 8083:8083
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/manufacturer
    depends_on:
      - postgres