version: "3"
services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 5435:5435
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manufacturer
  manufacturers:
    image: ejmric/manufacturers
    ports:
      - 8083:8083
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5435/manufacturer
    depends_on:
      - postgres