apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-manufacturers-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-manufacturers
    spec:
      containers:
        - image: centos/postgresql-94-centos7
          name: postgres-manufacturers
          env:
            - name: POSTGRESQL_USER
              value: dbuser
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: manufacturer
          ports:
          - containerPort: 5435
            protocol: TCP