apiVersion: v1
kind: Service
metadata:
  name: postgres-manufacturers
spec:
  type: ClusterIP
  ports:
  - port: 5435
    protocol: TCP
    targetPort: 5435
  selector:
    app: postgres-manufacturers